### ISSUE TITLE
Update Template for latest version of Dokuwiki

### ISSUE THREAD

**Issue by meskarune** [selfthinker/dokuwiki_template_starter#13]
The current template on the dokuwiki site hasn't been updated since 2015. Is this theme still being maintained?

**Comment by selfthinker** [comment]
Nothing important has changed in DokuWiki which affects templates since 2015. This template still works as always in the latest DokuWiki version and doesn't need an update.

The only thing to do is to future-proof it to use the new menu (#14) but that doesn't affect users yet (only when the old menu disappears in a couple of years).
